# Generated by Django 5.2.3 on 2025-07-03 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rx_number', models.CharField(blank=True, max_length=50, null=True)),
                ('department_number', models.CharField(blank=True, max_length=4, null=True)),
                ('dob', models.DateField()),
                ('pharmacy_or_doctor_name', models.CharField(max_length=255)),
                ('contact_details', models.CharField(max_length=255)),
                ('date_filled', models.CharField(max_length=50)),
                ('date_expired', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('store_number', models.CharField(max_length=50)),
                ('rx_image', models.ImageField(upload_to='prescriptions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('qty', models.CharField(max_length=20)),
                ('refills_info', models.CharField(max_length=255)),
                ('side_effects', models.TextField()),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='prescriptions.prescription')),
            ],
        ),
    ]
